
name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  job1:
    steps:
      - uses: actions/checkout@v4
      - run: echo "Run your script here"